const busInfo = [
  {
    city: "Colombo",
    fare: 1100,
    Name: "Mighty Travels",
    depature: 10,
    arrival: 12,
    seats: 30,
  },
  {
    city: "Colombo",
    fare: 1100,
    Name: "Rathna Travels",
    depature: 9,
    arrival: 11,
    seats: 25,
  },
  {
    city: "Colombo",
    fare: 1100,
    Name: "Laksmi express",
    depature: 11,
    arrival: 13,
    seats: 35,
  },
  {
    city: "Colombo",
    fare: 1100,
    Name: "Kit Travels",
    depature: 12,
    arrival: 14,
    seats: 15,
  },
  {
    city: "Galle",
    fare: 1100,
    Name: "Rathna Travels",
    depature: 9,
    arrival: 11,
    seats: 25,
  },
  {
    city: "Galle",
    fare: 1000,
    Name: "Marina Travels",
    depature: 8,
    arrival: 10,
    seats: 15,
  },
  {
    city: "Galle",
    fare: 1000,
    Name: "Laksmi Travels",
    depature: 9,
    arrival: 11,
    seats: 11,
  },
  {
    city: "Galle",
    fare: 1000,
    Name: "PPN express",
    depature: 11,
    arrival: 13,
    seats: 25,
  },
  {
    city: "Kurunegala",
    fare: 1200,
    Name: "Rathna Travels",
    depature: 8,
    arrival: 10,
    seats: 30,
  },
  {
    city: "Kurunegala",
    fare: 1200,
    Name: "Shree Travels",
    depature: 9,
    arrival: 11,
    seats: 25,
  },
  {
    city: "Kurunegala",
    fare: 1200,
    Name: "JGP Travels",
    depature: 6,
    arrival: 8,
    seats: 15,
  },
  {
    city: "Kaduwela",
    fare: 1300,
    Name: "Mighty Travels",
    depature: 6,
    arrival: 8,
    seats: 10,
  },
  {
    city: "Kaduwela",
    fare: 1300,
    Name: "AGT Travels",
    depature: 8,
    arrival: 10,
    seats: 25,
  },
  {
    city: "Kaduwela",
    fare: 1300,
    Name: "Rathna Travels",
    depature: 9,
    arrival: 11,
    seats: 15,
  },
  {
    city: "Kaduwela",
    fare: 1300,
    Name: "Kit Travels",
    depature: 10,
    arrival: 12,
    seats: 20,
  },
  {
    city: "Mathugama",
    fare: 1250,
    Name: "LQ Lines Travels",
    depature: 11,
    arrival: 13,
    seats: 30,
  },
  {
    city: "Mathugama",
    fare: 1250,
    Name: "PPN express",
    depature: 12,
    arrival: 14,
    seats: 25,
  },
  {
    city: "Mathugama",
    fare: 1250,
    Name: "Marina Travels",
    depature: 13,
    arrival: 15,
    seats: 15,
  },
  {
    city: "Mathugama",
    fare: 1250,
    Name: "Shree Travels",
    depature: 14,
    arrival: 16,
    seats: 20,
  },
];
export default busInfo;
